### ISSUE TITLE
Edits gone after update

### ISSUE THREAD

**Issue by mbuhnici** [getgrav/grav-skeleton-gateway-site#3]
All the styling changes I have done have simply vanished after a theme update. Could you insert a CSS file that sits outside the theme folder so that we can add there the classes we want to amend?

Thanks

**Comment by flaviocopes** [comment]
Updating any theme will overwrite the changes. You can use a plugin such as "Custom CSS" https://github.com/getgrav/grav-plugin-custom-css to add CSS outside of the theme, or simply use a Git repository to determine the changes made in an update, and re-apply your own changes if needed.
