### ISSUE TITLE
Can't install Admin Plugin: ERROR Missing .dependencies file in user/ folder

### ISSUE THREAD

**Issue by phivk** [getgrav/grav-skeleton-gateway-site#5]
I've downloaded the zip of the Gateway skeleton via the [grav downloads page](https://getgrav.org/downloads/skeletons). When I try to install the admin plugin I get this error:

    % ./bin/grav install admin
    ERROR Missing .dependencies file in user/ folder
    ERROR invalid YAML in .dependencies

Although I see this repo contains a `.dependencies` [file](https://github.com/getgrav/grav-skeleton-gateway-site/blob/master/.dependencies), the downloaded zip doesn't.

I've tried creating `user/.dependencies` both empty and with the content from the file in the repo, but the error persists.

How can I get the `bin/grav install` command to work?

**Comment by flaviocopes** [comment]
As replied in Slack, use `bin/gpm install admin`
